language: node_js
install:
  - npm install

stages:
  - "Tests"

jobs:
  include:
    - stage: "Tests"      # Naming the Tests stage
      name: "Unit Tests"  # Names the first Tests stage job
      script: "./test/test.js"