dist: xenial
language: node_js
node_js:
  - 16
python:
  - "3.6"
before_install:
  - pyenv install 3.6.0
  - pyenv global 3.6.0
  - npm config set python "/opt/pyenv/versions/3.6.0" # where pyenv installs python
install:
  - npm install

stages:
  - "Tests"

jobs:
  include:
    - stage: "Tests"      # Naming the Tests stage
      name: "Unit Tests"  # Names the first Tests stage job
      script: "mocha"