language: node_js
node_js:
  - 14
before_install: if [[ `npm -v` != 7* ]]; then npm i -g npm@7; fi
install:
  - npm install

stages:
  - "Tests"

jobs:
  include:
    - stage: "Tests"      # Naming the Tests stage
      name: "Unit Tests"  # Names the first Tests stage job
      script: "mocha"