version: "2.0"
services:
  tundrabot:
    build:
      context: .
    image: tundrabot:latest
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGOOSE_PROTOCOL=mongodb
      - MONGOOSE_URL=mongodb:27017
      - MONGOOSE_USERNAME=root
      - MONGOOSE_PASSWORD=example
    networks:
      - tundrabot-network
  mongodb:
    image: mongo:4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=TundraBotDev
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - tundrabot-network
networks:
  tundrabot-network:
    driver: bridge
volumes:
  mongodb_data_container: